# Site settings
title:       Pulent
email:       nikola@pulent.com
author:      Nikola Balic
description: "Supporting growing organisations in meeting their ambitions."
baseurl:     ""
url:         "https://pulent.com"
date_format: "%b %-d, %Y"
header_pages:
 - me.md
 - contact.html

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

google_analytics: UA-102548855-1

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true

# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Disqus post comments
disqus_shortname:

# Social icons
github_username:
twitter_username: nibalic
linkedin_username: nikola.balic

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share:'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
    post_footer:    'Lorem ipsum'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    :title
paginate:     4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
